// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Artisan = sequelize.define('artisan', {
    artisanId: {
      type: DataTypes.INTEGER,
      field: 'artisan_id',
      primaryKey: true,
      autoIncrement: true,
      allowNull: true
    },
    artisanName: {
      type: DataTypes.STRING,
      field: 'artisan_name',
      allowNull: false
    },
    aboutArtisan: {
      type: DataTypes.STRING,
      field: 'about_artisan',
      allowNull: true
    },
    artisanGroup: {
      type: DataTypes.STRING,
      field: 'artisan_group',
      allowNull: true
    },
    artisanEmail: {
      type: DataTypes.STRING,
      field: 'artisan_email',
    },
    artisanPicture: {
      type: DataTypes.STRING,
      field: 'artisan_picture',
    },
    artisanContactNumber: {
      type: DataTypes.STRING,
      field: 'artisan_contact_number',
    },
    artisanAddress: {
      type: DataTypes.STRING,
      field: 'artisan_address',
    },
    artisanBirthday: {
      type: DataTypes.DATE,
      field: 'artisan_birthday',
    },
    isActive: {
      type: DataTypes.BOOLEAN,
      field: 'is_active',
      defaultValue: Sequelize.literal('true'),
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'artisan',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Artisan.associate = (models) => {
  };

  return Artisan;
};
