// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Product = sequelize.define('product', {
    productId: {
      type: DataTypes.INTEGER,
      field: 'product_id',
      primaryKey: true,
      autoIncrement: true,
      allowNull: true
    },
    name: {
      type: DataTypes.STRING,
      field: 'name',
      allowNull: false
    },
    storyCode: {
      type: DataTypes.STRING,
      field: 'story_code',
      allowNull: false
    },
    productDetail: {
      type: DataTypes.STRING,
      field: 'product_detail',
    },
    productMaterial: {
      type: DataTypes.STRING,
      field: 'product_material',
    },
    craftTechnique: {
      type: DataTypes.STRING,
      field: 'craft_technique',
    },
    skuId: {
      type: DataTypes.STRING,
      field: 'sku_id',
    },
    productImage1: {
      type: DataTypes.STRING,
      field: 'product_image1',
    },
    productImage2: {
      type: DataTypes.STRING,
      field: 'product_image2',
    },
    productImage3: {
      type: DataTypes.STRING,
      field: 'product_image3',
    },
    productImage4: {
      type: DataTypes.STRING,
      field: 'product_image4',
    },
    productImage5: {
      type: DataTypes.STRING,
      field: 'product_image5',
    },
    productImage6: {
      type: DataTypes.STRING,
      field: 'product_image6',
    },
    productImage7: {
      type: DataTypes.STRING,
      field: 'product_image7',
    },
    productImage8: {
      type: DataTypes.STRING,
      field: 'product_image8',
    },
    productImage9: {
      type: DataTypes.STRING,
      field: 'product_image9',
    },
    productImage10: {
      type: DataTypes.STRING,
      field: 'product_image10',
    },
    isActive: {
      type: DataTypes.BOOLEAN,
      field: 'is_active',
      defaultValue: Sequelize.literal('true'),
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'product',
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Product.associate = (models) => {
    Product.belongsTo(models.collection, {
      foreignKey: {
        name: 'collectionId',
        field: 'collection_id',
      },
      target: {
        name: 'collection_id',
      },
      as: 'collection',
    });
    Product.belongsTo(models.artisan, {
      foreignKey: {
        name: 'artisanId',
        field: 'artisan_id',
      },
      target: {
        name: 'artisan_id',
      },
      as: 'artisan',
    });
  };

  return Product;
};
